// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4J0JXCkvpcPyBYHAj2KF2IzCtEvEUASU',
    appId: '1:883117483581:web:44a3aec3641552ba28ec54',
    messagingSenderId: '883117483581',
    projectId: 'gestionscolariteuatm',
    authDomain: 'gestionscolariteuatm.firebaseapp.com',
    storageBucket: 'gestionscolariteuatm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1JJCjEXxuzUKhgKqG2DCPpdl0BDvSSyA',
    appId: '1:883117483581:android:8efe4839dd510eb628ec54',
    messagingSenderId: '883117483581',
    projectId: 'gestionscolariteuatm',
    storageBucket: 'gestionscolariteuatm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaYFWTcZxcY0i2StSLZJa2iXSn_tAE35s',
    appId: '1:883117483581:ios:979b6647b0830bf928ec54',
    messagingSenderId: '883117483581',
    projectId: 'gestionscolariteuatm',
    storageBucket: 'gestionscolariteuatm.firebasestorage.app',
    iosBundleId: 'com.example.uatmPaiements',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaYFWTcZxcY0i2StSLZJa2iXSn_tAE35s',
    appId: '1:883117483581:ios:979b6647b0830bf928ec54',
    messagingSenderId: '883117483581',
    projectId: 'gestionscolariteuatm',
    storageBucket: 'gestionscolariteuatm.firebasestorage.app',
    iosBundleId: 'com.example.uatmPaiements',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4J0JXCkvpcPyBYHAj2KF2IzCtEvEUASU',
    appId: '1:883117483581:web:8a05c1424ec3c07c28ec54',
    messagingSenderId: '883117483581',
    projectId: 'gestionscolariteuatm',
    authDomain: 'gestionscolariteuatm.firebaseapp.com',
    storageBucket: 'gestionscolariteuatm.firebasestorage.app',
  );
}
